# Generated by Django 5.0 on 2023-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
        migrations.AddField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
